# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200401_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.TextField(default=''),
        ),
    ]
