# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.TextField(default=''),
        ),
    ]
